apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-example-dex
stringData:
  config.yaml: |-
    issuer: http://dex.localtest.me
    storage:
      config:
        inCluster: true
      type: kubernetes
    logger:
      level: debug
    web:
      http: 0.0.0.0:5556
    oauth2: 
      alwaysShowLoginScreen: false
      skipApprovalScreen: true
    staticClients:
    - id: oauth2-proxy
      name: OAuth2 Proxy
      redirectURIs:
      - http://oauth2-proxy.localtest.me/oauth2/callback
      secret: b2F1dGgyLXByb3h5LWNsaWVudC1zZWNyZXQK
    enablePasswordDB: true
    staticPasswords:
    - email: admin@example.com
      hash: $2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W
      userID: 08a8684b-db88-4b73-90a9-3cd1661f5466
      username: admin
    expiry:
      idTokens: 1h
      signingKeys: 4h